;;
; @brief This file contains registeres used as variables
;;

        cblock 0x20
status_temp         ; 0x20
w_temp              ; 0x21
led                 ; 0x22
darker              ; 0x23
intensity_high      ; 0x24
intensity_low       ; 0x25
intensity_ww_high   ; 0x26
intensity_ww_low    ; 0x27
intensity_cw_high   ; 0x28
intensity_cw_low    ; 0x29
pointer             ; 0x2a
pointer_ww          ; 0x2b
pointer_cw          ; 0x2c
pointer_sub_high    ; 0x2d
pointer_sub_low     ; 0x2e
        endc
